### ISSUE TITLE
There is no 404 error code when the room does not exist

### ISSUE THREAD

**Issue by CatHuyuH24** [eNKay2408/Hotel-Management#18]
- Currently, when trying to update  a room, if it doesn't exists, the RoomController returns a message without a proper response code (particularly 404)
![image](https://github.com/user-attachments/assets/a05312b9-310d-430b-8812-96acf8032733)

_This has been discovered recently when reviewing the test cases of RoomController._

**For best practice, aid in future debugging and to pass the tests, please add the approriate response codes ASAP**

**Comment by simpleHuy** [comment]
i fixed it in branch fix/Controller
