### ISSUE TITLE
There is no 400 response code when the client's update request misses a field 

### ISSUE THREAD

**Issue by CatHuyuH24** [eNKay2408/Hotel-Management#19]
When the client's request misses a field info while performing an update, the RoomController doesn't respond with the response code 404 - Bad request.
**Currently, the received code is 200 (OK)**
![image](https://github.com/user-attachments/assets/141923d9-55d2-45ba-b4c3-3c799eb5bbd5)

![image](https://github.com/user-attachments/assets/fab989ac-1e8a-4fe6-bc54-215ce81f6090)

**Please response with the proper code to align with best practice, help with maintainability and to pass the test.**

**Comment by simpleHuy** [comment]
i fixed it in branch fix/Controller
