### ISSUE TITLE
Fix: Occupancy Details is saving Rate instead of Rental Days

### ISSUE THREAD

**Issue by eNKay2408** [eNKay2408/Hotel-Management#21]
### Description
- In the DB, the OCCUPANCY_HAS_ROOM table is currently storing Rate instead of RentalDays as designed
- This results in the API returning Rate, making it impossible to visualize the column chart with Rental Days for the Occupancy Report

### Expected Behavior
- The RentalDays field must be stored and returned in the DB and API
- The total RentalDays of the Rooms must be equal to the TotalRentalDays in the API

#### Current DB
![image](https://github.com/user-attachments/assets/14476c18-0bc1-45ea-8ac9-2d7cfc1f126d)

#### Design DB
![image](https://github.com/user-attachments/assets/f63c4d0c-c1ae-46e5-8dca-9fc742044132)

**Comment by OriginalNVK** [comment]
This issue solved

**Comment by CatHuyuH24** [comment]
I'm closing the issue as it's solved...
